package de.learnlib.algorithm.c3al;

import org.checkerframework.checker.nullness.qual.Nullable;

import de.learnlib.query.Query;
import net.automatalib.automaton.concept.Output;

/*
 * The EventHandler defines the termination criteria, and hypothesis selection criteria for C3AL.
 * It is provided with every hypothesis generated by C3AL (through hypEvent) and every query posed by C3Al
 * (through queryEvent). If either of these functions return a non-null hypothesis, C3AL will terminate,
 * accepting it as the final hypothesis to be returned.
 */
public interface EventHandler<M extends Output<I, D>, I, D> {
    @Nullable
    M hypEvent(@Nullable M hyp);

    @Nullable
    M queryEvent(Query<I, D> query);

    void reset();
}